### ISSUE TITLE
add gloss, matte, metallic

### ISSUE THREAD

**Issue by dhesru** [lupangsogood/Project_senior#1]
Hi, any idea how to add gloss/matte/mettalic finished to lips?

**Comment by lupangsogood** [comment]
> 
> 
> Hi, any idea how to add gloss/matte/mettalic finished to lips?

Sorry,i have no idea for any lipstick type. But i think u can mask any texture(gloss/matte/mettalic) on lips after apply color.
 I hope it can really help u.
